config/routes.rb
Rails.application.routes.draw do
  # get "/", to: "flats#index"
  root to: "flats#index"

  get '/flats/:id', to: 'flats#show', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
  before_action :set_flats

  def index
  end

  def show
    @flat = @flats.find { |flat| flat['id'] == params['id'].to_i }
  end

  private

  def set_flats
    @flats = JSON.parse(open(URL).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>NoDB AirBnB</h1>
<ul>
  <% @flats.each do |flat| %>
    <li class="flat-card">
      <img src="<%= flat['imageUrl'] %>" width=200>
      <p><%= link_to flat['name'], flat_path(flat['id']) %></p>
      <p><%= "#{flat['priceCurrency']} #{flat['price']}" %></p>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<%= link_to 'Back to index', root_path %>
<h1><%= @flat['name'] %></h1>
<img src="<%= @flat['imageUrl'] %>" width=200>
<p>
  <span class="flat-currency"><%= @flat['priceCurrency'] %></span>
  <span class="flat-price"><%= @flat['price'] %></span>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NodbAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>